version: '3.4'

# NOTE: Port mapping is:
#  - "HOST:CONTAINER"
services:
  web:
    command: bash -c "yarn run web:start"
    environment:
      NODE_ENV: development
      PORT: 8080
    ports:
      - "8080:8080"

  api:
    command: bash -c 'cd /app; (yarn run watch &); yarn run api:start'
    environment:
      NODE_ENV: development
      DB_NAME: dt-townies
    ports:
      - "9229:9229"

  db:
    ports:
      - "5433:5432"

volumes:
  db-pgdata:
